version: '3'

services:
  db:
    image: mysql:5.7
    container_name: nextcloud-db
    restart: always
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    networks:
      - nextcloud-net
    environment:
      MYSQL_ROOT_PASSWORD: nextcloudf
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    networks:
      - nextcloud-net

  nextcloud:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 8083:80
    volumes:
      - nextcloud-data:/var/www/html
    networks:
      - nextcloud-net
    environment:
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    depends_on:
      - db

volumes:
  nextcloud-db-data:
  nextcloud-data:

networks:
  nextcloud-net:
    driver: bridge
